/**
 * Report utility functions for markdown generation and health score helpers.
 */

/**
 * Returns a color hex string based on health score.
 * @param {number} score - 0 to 100
 * @returns {string} hex color
 */
export function getHealthScoreColor(score) {
  if (score >= 85) return '#4ECDC4';
  if (score >= 75) return '#F5A623';
  if (score >= 60) return '#FF6B35';
  return '#FF2D2D';
}

/**
 * Returns a human-readable label for a grade string.
 * @param {string} grade - e.g. "A+", "A", "B+", "B", "C", "D", "F"
 * @returns {string}
 */
export function getGradeLabel(grade) {
  const map = {
    'A+': 'Excellent',
    'A': 'Great',
    'A-': 'Very Good',
    'B+': 'Good',
    'B': 'Above Average',
    'B-': 'Decent',
    'C+': 'Needs Work',
    'C': 'Below Average',
    'C-': 'Poor',
    'D+': 'Concerning',
    'D': 'Critical',
    'D-': 'Severe',
    'F': 'Failing',
  };
  return map[grade] || 'Unknown';
}

/**
 * Generate a single bug as markdown.
 * @param {object} bug
 * @returns {string}
 */
export function generateBugMarkdown(bug) {
  let md = `### [${bug.severity.toUpperCase()}] ${bug.title}\n\n`;
  md += `**ID:** \`${bug.id}\`\n`;
  if (bug.category) md += `**Category:** ${bug.category}\n`;
  md += `\n${bug.description}\n\n`;

  if (bug.stepsToReproduce?.length) {
    md += `**Steps to Reproduce:**\n`;
    bug.stepsToReproduce.forEach((step, i) => {
      md += `${i + 1}. ${step}\n`;
    });
    md += `\n`;
  }

  md += `**Expected:** ${bug.expected}\n`;
  md += `**Actual:** ${bug.actual}\n`;

  if (bug.consoleOutput) {
    md += `\n**Console Output:**\n\`\`\`\n${bug.consoleOutput}\n\`\`\`\n`;
  }

  md += `\n---\n\n`;
  return md;
}

/**
 * Generate a full markdown report.
 * @param {object} report
 * @returns {string}
 */
export function generateMarkdownReport(report) {
  const {
    url,
    timestamp,
    duration_ms,
    testsRun,
    summary,
    vitals,
    sourceAudit,
    bugs,
    healthScore,
    grade,
  } = report;

  const totalIssues = Object.values(summary).reduce((a, b) => a + b, 0);

  let md = `# Playwright QA Suite — Bug Report\n\n`;

  // Health score section
  if (healthScore !== undefined) {
    md += `## Health Score: ${healthScore}/100 (${grade || 'N/A'}) — ${getGradeLabel(grade)}\n\n`;
  }

  md += `| Field | Value |\n|-------|-------|\n`;
  md += `| URL | ${url} |\n`;
  md += `| Date | ${new Date(timestamp).toLocaleString()} |\n`;
  md += `| Duration | ${(duration_ms / 1000).toFixed(1)}s |\n`;
  md += `| Tests Run | ${testsRun} |\n`;
  md += `| Total Issues | ${totalIssues} |\n`;
  md += `\n`;

  md += `## Severity Summary\n\n`;
  md += `| Severity | Count |\n|----------|-------|\n`;
  Object.entries(summary).forEach(([sev, count]) => {
    md += `| ${sev.charAt(0).toUpperCase() + sev.slice(1)} | ${count} |\n`;
  });
  md += `\n`;

  if (vitals) {
    md += `## Core Web Vitals\n\n`;
    md += `| Metric | Value | Rating |\n|--------|-------|--------|\n`;
    Object.entries(vitals).forEach(([name, data]) => {
      md += `| ${name.toUpperCase()} | ${data.value}${data.unit} | ${data.rating} |\n`;
    });
    md += `\n`;
  }

  if (sourceAudit) {
    md += `## Source Audit\n\n`;
    md += `- **Third-party Scripts:** ${sourceAudit.thirdPartyScripts}\n`;
    md += `- **Console Errors:** ${sourceAudit.consoleErrors}\n`;
    md += `- **Inline Event Handlers:** ${sourceAudit.inlineEventHandlers}\n`;
    md += `- **Total DOM Nodes:** ${sourceAudit.totalDomNodes?.toLocaleString() || 'N/A'}\n`;
    if (sourceAudit.analyticsProviders?.length) {
      md += `- **Analytics Providers:** ${sourceAudit.analyticsProviders.join(', ')}\n`;
    }
    if (sourceAudit.missingMetaTags?.length) {
      md += `- **Missing Meta Tags:** ${sourceAudit.missingMetaTags.join(', ')}\n`;
    }
    md += `\n`;
  }

  md += `## Issues (${bugs.length})\n\n`;
  bugs.forEach((bug) => {
    md += generateBugMarkdown(bug);
  });

  md += `\n---\n*Report generated by Playwright QA Suite*\n`;

  return md;
}
